In [1]:
import os
import csv
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt

In [2]:
wait_times = pd.read_csv('Wait_Times_By_Centers.csv')

wait_times = pd.DataFrame(wait_times)

wait_times

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,All Organs,Kidney,Liver,Pancreas,Kidney / Pancreas,Heart,Lung,Heart / Lung,Intestine,Abdominal Wall,Head & Neck: Craniofacial,GU: Uterus,Upper Limb: Bilateral,Upper Limb: Unilateral,"Face, Scalp"
0,All Centers,All Center States,All Time,NaN,"107,888","91,242","11,896",897.0,"1,702","3,515",983.0,48.0,212.0,3.0,2.0,6.0,3.0,3.0,1.0
1,NaN,NaN,< 30 Days,NaN,"4,668","3,281",878,50.0,127,329,192.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,30 to < 90 Days,NaN,"6,538","4,979","1,032",58.0,149,365,148.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
3,NaN,NaN,90 Days to < 6 Months,NaN,"10,360","8,158","1,563",90.0,236,445,153.0,6.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NaN,NaN,6 Months to < 1 Year,NaN,"14,171","11,530","1,976",110.0,302,482,117.0,7.0,31.0,1.0,0.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,NaN,NaN,< 30 Days,NaN,2,2,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4880,NaN,NaN,30 to < 90 Days,NaN,4,4,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4881,NaN,NaN,90 Days to < 6 Months,NaN,10,9,0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4882,NaN,NaN,6 Months to < 1 Year,NaN,23,23,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4883,NaN,NaN,1 Year to < 2 Years,NaN,3,3,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [3]:
list(wait_times.columns)

['Unnamed: 0',
 'Unnamed: 1',
 'Unnamed: 2',
 'Unnamed: 3',
 'All Organs',
 'Kidney',
 'Liver',
 'Pancreas',
 'Kidney / Pancreas',
 'Heart',
 'Lung',
 'Heart / Lung',
 'Intestine',
 'Abdominal Wall',
 'Head & Neck: Craniofacial',
 'GU: Uterus',
 'Upper Limb: Bilateral',
 'Upper Limb: Unilateral',
 'Face, Scalp']

In [4]:
wait_times = wait_times.drop(columns='Unnamed: 3')

wait_times

,Unnamed: 0,Unnamed: 1,Unnamed: 2,All Organs,Kidney,Liver,Pancreas,Kidney / Pancreas,Heart,Lung,Heart / Lung,Intestine,Abdominal Wall,Head & Neck: Craniofacial,GU: Uterus,Upper Limb: Bilateral,Upper Limb: Unilateral,"Face, Scalp"
0,All Centers,All Center States,All Time,"107,888","91,242","11,896",897.0,"1,702","3,515",983.0,48.0,212.0,3.0,2.0,6.0,3.0,3.0,1.0
1,NaN,NaN,< 30 Days,"4,668","3,281",878,50.0,127,329,192.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
2,NaN,NaN,30 to < 90 Days,"6,538","4,979","1,032",58.0,149,365,148.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
3,NaN,NaN,90 Days to < 6 Months,"10,360","8,158","1,563",90.0,236,445,153.0,6.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
4,NaN,NaN,6 Months to < 1 Year,"14,171","11,530","1,976",110.0,302,482,117.0,7.0,31.0,1.0,0.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,NaN,NaN,< 30 Days,2,2,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4880,NaN,NaN,30 to < 90 Days,4,4,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4881,NaN,NaN,90 Days to < 6 Months,10,9,0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4882,NaN,NaN,6 Months to < 1 Year,23,23,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4883,NaN,NaN,1 Year to < 2 Years,3,3,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [5]:
wait_times['Unnamed: 0'] = wait_times['Unnamed: 0'].fillna(method='ffill')

wait_times['Unnamed: 1'] = wait_times['Unnamed: 1'].fillna(method='ffill')

wait_times

,Unnamed: 0,Unnamed: 1,Unnamed: 2,All Organs,Kidney,Liver,Pancreas,Kidney / Pancreas,Heart,Lung,Heart / Lung,Intestine,Abdominal Wall,Head & Neck: Craniofacial,GU: Uterus,Upper Limb: Bilateral,Upper Limb: Unilateral,"Face, Scalp"
0,All Centers,All Center States,All Time,"107,888","91,242","11,896",897.0,"1,702","3,515",983.0,48.0,212.0,3.0,2.0,6.0,3.0,3.0,1.0
1,All Centers,All Center States,< 30 Days,"4,668","3,281",878,50.0,127,329,192.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
2,All Centers,All Center States,30 to < 90 Days,"6,538","4,979","1,032",58.0,149,365,148.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
3,All Centers,All Center States,90 Days to < 6 Months,"10,360","8,158","1,563",90.0,236,445,153.0,6.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
4,All Centers,All Center States,6 Months to < 1 Year,"14,171","11,530","1,976",110.0,302,482,117.0,7.0,31.0,1.0,0.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,2,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,4,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,10,9,0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,23,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,3,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [6]:
wait_times = wait_times.rename(columns={'Unnamed: 0':'Center Name','Unnamed: 1':'Center States','Unnamed: 2':'Wait Time'})

wait_times

,Center Name,Center States,Wait Time,All Organs,Kidney,Liver,Pancreas,Kidney / Pancreas,Heart,Lung,Heart / Lung,Intestine,Abdominal Wall,Head & Neck: Craniofacial,GU: Uterus,Upper Limb: Bilateral,Upper Limb: Unilateral,"Face, Scalp"
0,All Centers,All Center States,All Time,"107,888","91,242","11,896",897.0,"1,702","3,515",983.0,48.0,212.0,3.0,2.0,6.0,3.0,3.0,1.0
1,All Centers,All Center States,< 30 Days,"4,668","3,281",878,50.0,127,329,192.0,8.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0
2,All Centers,All Center States,30 to < 90 Days,"6,538","4,979","1,032",58.0,149,365,148.0,6.0,18.0,0.0,0.0,0.0,0.0,0.0,0.0
3,All Centers,All Center States,90 Days to < 6 Months,"10,360","8,158","1,563",90.0,236,445,153.0,6.0,19.0,0.0,0.0,0.0,0.0,0.0,0.0
4,All Centers,All Center States,6 Months to < 1 Year,"14,171","11,530","1,976",110.0,302,482,117.0,7.0,31.0,1.0,0.0,0.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,2,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,4,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,10,9,0,0.0,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,23,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,3,0,0.0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [7]:
wait_times.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4884 entries, 0 to 4883
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Center Name                4884 non-null   object
 1   Center States              4884 non-null   object
 2   Wait Time                  4768 non-null   object
 3   All Organs                 4768 non-null   object
 4   Kidney                     4768 non-null   object
 5   Liver                      4768 non-null   object
 6   Pancreas                   4768 non-null   float64
 7   Kidney / Pancreas          4768 non-null   object
 8   Heart                      4768 non-null   object
 9   Lung                       4768 non-null   float64
 10  Heart / Lung               4768 non-null   float64
 11  Intestine                  4768 non-null   float64
 12  Abdominal Wall             4768 non-null   float64
 13  Head & Neck: Craniofacial  4768 non-null   float64
 14  GU: Uterus                 4768 non-null   float64
 15  Upper Limb: Bilateral      4768 non-null   float64
 16  Upper Limb: Unilateral     4768 non-null   float64
 17  Face, Scalp                4768 non-null   float64
dtypes: float64(10), object(8)
memory usage: 686.9+ KB

In [42]:
final_df = wait_times[['Center Name','Center States','Wait Time','Kidney','Liver','Pancreas','Heart']]

final_df = pd.DataFrame(final_df)

final_df

,Center Name,Center States,Wait Time,Kidney,Liver,Pancreas,Heart
0,All Centers,All Center States,All Time,"91,242","11,896",897.0,"3,515"
1,All Centers,All Center States,< 30 Days,"3,281",878,50.0,329
2,All Centers,All Center States,30 to < 90 Days,"4,979","1,032",58.0,365
3,All Centers,All Center States,90 Days to < 6 Months,"8,158","1,563",90.0,445
4,All Centers,All Center States,6 Months to < 1 Year,"11,530","1,976",110.0,482
...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,0,0.0,0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,0,0.0,0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,9,0,0.0,1
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,0,0.0,0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,0,0.0,0

In [43]:
final_df['Kidney']=final_df['Kidney'].str.replace(',','')

final_df['Liver']=final_df['Liver'].str.replace(',','')

final_df['Heart']=final_df['Heart'].str.replace(',','')

final_df

,Center Name,Center States,Wait Time,Kidney,Liver,Pancreas,Heart
0,All Centers,All Center States,All Time,91242,11896,897.0,3515
1,All Centers,All Center States,< 30 Days,3281,878,50.0,329
2,All Centers,All Center States,30 to < 90 Days,4979,1032,58.0,365
3,All Centers,All Center States,90 Days to < 6 Months,8158,1563,90.0,445
4,All Centers,All Center States,6 Months to < 1 Year,11530,1976,110.0,482
...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,0,0.0,0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,0,0.0,0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,9,0,0.0,1
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,0,0.0,0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,0,0.0,0

In [44]:
mean_group.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4768 entries, 0 to 4883
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Center Name    4768 non-null   object
 1   Center States  4768 non-null   object
 2   Wait Time      4768 non-null   object
 3   Kidney         4768 non-null   int64
 4   Liver          4768 non-null   int64
 5   Pancreas       4768 non-null   int64
 6   Heart          4768 non-null   int64
dtypes: int64(4), object(3)
memory usage: 458.0+ KB

In [45]:
final_df = final_df.dropna(subset=['Wait Time'])

final_df

,Center Name,Center States,Wait Time,Kidney,Liver,Pancreas,Heart
0,All Centers,All Center States,All Time,91242,11896,897.0,3515
1,All Centers,All Center States,< 30 Days,3281,878,50.0,329
2,All Centers,All Center States,30 to < 90 Days,4979,1032,58.0,365
3,All Centers,All Center States,90 Days to < 6 Months,8158,1563,90.0,445
4,All Centers,All Center States,6 Months to < 1 Year,11530,1976,110.0,482
...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,0,0.0,0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,0,0.0,0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,9,0,0.0,1
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,0,0.0,0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,0,0.0,0

In [46]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 4768 entries, 0 to 4883
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Center Name    4768 non-null   object
 1   Center States  4768 non-null   object
 2   Wait Time      4768 non-null   object
 3   Kidney         4768 non-null   object
 4   Liver          4768 non-null   object
 5   Pancreas       4768 non-null   float64
 6   Heart          4768 non-null   object
dtypes: float64(1), object(6)
memory usage: 298.0+ KB

In [54]:
final_df['Kidney'].astype(int)
final_df['Liver'].astype(int)
final_df['Heart'].astype(int)
final_df['Pancreas'].astype(int)

final_df

,Center Name,Center States,Wait Time,Kidney,Liver,Pancreas,Heart
459,ALCH-TX1 Children's of Alabama,Alabama,All Time,15,2,0.0,6
460,ALCH-TX1 Children's of Alabama,Alabama,< 30 Days,2,0,0.0,1
461,ALCH-TX1 Children's of Alabama,Alabama,30 to < 90 Days,0,1,0.0,0
463,ALCH-TX1 Children's of Alabama,Alabama,90 Days to < 6 Months,3,0,0.0,0
464,ALCH-TX1 Children's of Alabama,Alabama,6 Months to < 1 Year,3,0,0.0,2
...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,0,0.0,0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,0,0.0,0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,9,0,0.0,1
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,0,0.0,0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,0,0.0,0

In [55]:
center_list = ['All Centers']

not_ACS_list = ['All Center States']

final_df = final_df[final_df['Center Name'].isin(center_list) == False]

final_df = final_df[final_df['Center States'].isin(not_ACS_list) == False]

final_df

,Center Name,Center States,Wait Time,Kidney,Liver,Pancreas,Heart
459,ALCH-TX1 Children's of Alabama,Alabama,All Time,15,2,0.0,6
460,ALCH-TX1 Children's of Alabama,Alabama,< 30 Days,2,0,0.0,1
461,ALCH-TX1 Children's of Alabama,Alabama,30 to < 90 Days,0,1,0.0,0
463,ALCH-TX1 Children's of Alabama,Alabama,90 Days to < 6 Months,3,0,0.0,0
464,ALCH-TX1 Children's of Alabama,Alabama,6 Months to < 1 Year,3,0,0.0,2
...,...,...,...,...,...,...,...
4879,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,< 30 Days,2,0,0.0,0
4880,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,30 to < 90 Days,4,0,0.0,0
4881,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,90 Days to < 6 Months,9,0,0.0,1
4882,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,6 Months to < 1 Year,23,0,0.0,0
4883,WVWU-TX1 West Virginia University Hospitals Inc.,West Virginia,1 Year to < 2 Years,3,0,0.0,0

In [53]:
x = final_df['Pancreas']

for l in x: 
    print(l)

0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
0.0
0.0
2.0
2.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
2.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
1.0
2.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
2.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
1.0
2.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
2.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
19.0
0.0
1.0
0.0
0.0
3.0
1.0
5.0
9.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
21.0
0.0
0.0
1.0
2.0
2.0
3.0
4.0
9.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.0
0.0
4.0
0.0
3.0
2.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
24.0
2.0
4.0
2.0
3.0
5.0
0.0
7.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
17.0
1.0
3.0
1.0
5.0
4.0
2.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
8.0
1.0
1.0
1.0
2.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
2.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.0
2.0
0.0
0.0
1.0
2.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
13.0
1.0
1.0
0.0
0.0
6.0
1.0
2.0
2.0
20.0
2.0
3.0
3.0
1.0
8.0
3.0
0.0
0.0
2.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
21.0
0.0
1.0
0.0
1.0
2.0
2.0
6.0
9.0
2.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
19.0
1.0
2.0
3.0
4.0
5.0
3.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
1.0
0.0
1.0
1.0
0.0
0.0
0.0
9.0
0.0
0.0
1.0
0.0
0.0
5.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
14.0
0.0
1.0
0.0
2.0
3.0
3.0
3.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
0.0
0.0
3.0
2.0
0.0
0.0
13.0
1.0
1.0
1.0
1.0
4.0
3.0
2.0
0.0
16.0
2.0
1.0
4.0
2.0
3.0
2.0
1.0
1.0
9.0
0.0
0.0
1.0
2.0
1.0
1.0
1.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
27.0
0.0
2.0
4.0
4.0
4.0
4.0
5.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
0.0
1.0
1.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
43.0
1.0
0.0
7.0
7.0
9.0
12.0
3.0
4.0
88.0
3.0
5.0
5.0
2.0
12.0
6.0
15.0
40.0
2.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
35.0
1.0
2.0
4.0
10.0
12.0
3.0
1.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
1.0
0.0
3.0
1.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
2.0
1.0
0.0
0.0
4.0
1.0
0.0
1.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
11.0
0.0
0.0
1.0
4.0
2.0
1.0
2.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
2.0
0.0
1.0
2.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
1.0
0.0
0.0
1.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
37.0
1.0
1.0
1.0
1.0
7.0
5.0
5.0
16.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
7.0
0.0
0.0
1.0
2.0
0.0
2.0
2.0
0.0
38.0
2.0
2.0
4.0
16.0
10.0
1.0
1.0
2.0
46.0
4.0
2.0
4.0
5.0
5.0
10.0
12.0
4.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.0
0.0
0.0
1.0
0.0
1.0
2.0
2.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
4.0
2.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
21.0
3.0
1.0
0.0
2.0
7.0
2.0
6.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15.0
0.0
1.0
3.0
1.0
2.0
3.0
5.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
1.0
1.0
0.0
0.0
0.0
0.0
1.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.0
1.0
1.0
2.0
0.0
3.0
0.0
1.0
2.0
5.0
0.0
0.0
1.0
2.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
5.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
3.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
12.0
0.0
1.0
1.0
0.0
0.0
2.0
1.0
7.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
0.0
0.0
1.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
15.0
3.0
1.0
1.0
2.0
4.0
2.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
0.0
1.0
0.0
1.0
1.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
13.0
0.0
0.0
0.0
4.0
5.0
3.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
10.0
2.0
0.0
0.0
1.0
6.0
0.0
1.0
0.0
3.0
1.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
6.0
0.0
0.0
2.0
0.0
3.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
9.0
1.0
0.0
2.0
0.0
2.0
2.0
1.0
1.0
2.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
10.0
0.0
0.0
0.0
1.0
2.0
3.0
3.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
1.0
2.0
1.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
5.0
0.0
1.0
2.0
0.0
1.0
0.0
0.0
1.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
1.0
1.0
0.0
0.0
0.0
1.0
0.0
21.0
0.0
3.0
5.0
4.0
3.0
4.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
3.0
0.0
0.0
1.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
1.0
1.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
14.0
1.0
2.0
2.0
3.0
1.0
3.0
0.0
2.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0
0.0

In [49]:
#Average Wait times for each type of transplant 
mean_df = final_df.groupby(['Center Name','Center States','Wait Time']).agg({'Kidney':'mean',
                                                                              'Liver':'mean',
                                                                              'Pancreas':'mean',
                                                                              'Heart':'mean'})

mean_df

DataError: No numeric types to aggregate

In [39]:
#total wait times 
total_df = mean_group.groupby(['Center Name','Center States','Wait Time']).agg({'Kidney':'sum',
                                                                              'Liver':'sum',
                                                                              'Pancreas':'sum',
                                                                              'Heart':'sum'})

total_df

                                                                                      Kidney  \
Center Name                                      Center States Wait Time
ALCH-TX1 Children's of Alabama                   Alabama       1 Year to < 2 Years         2
                                                               2 Years to < 3 Years        0
                                                               3 Years to < 5 Years        1
                                                               30 to < 90 Days             0
                                                               5 or More Years             4
...                                                                                      ...
WVWU-TX1 West Virginia University Hospitals Inc. West Virginia 30 to < 90 Days             4
                                                               6 Months to < 1 Year       23
                                                               90 Days to < 6 Months       9
                                                               < 30 Days                   2
                                                               All Time                   41

                                                                                      Liver  \
Center Name                                      Center States Wait Time
ALCH-TX1 Children's of Alabama                   Alabama       1 Year to < 2 Years        1
                                                               2 Years to < 3 Years       0
                                                               3 Years to < 5 Years       0
                                                               30 to < 90 Days            1
                                                               5 or More Years            0
...                                                                                     ...
WVWU-TX1 West Virginia University Hospitals Inc. West Virginia 30 to < 90 Days            0
                                                               6 Months to < 1 Year       0
                                                               90 Days to < 6 Months      0
                                                               < 30 Days                  0
                                                               All Time                   0

                                                                                      Pancreas  \
Center Name                                      Center States Wait Time
ALCH-TX1 Children's of Alabama                   Alabama       1 Year to < 2 Years           0
                                                               2 Years to < 3 Years          0
                                                               3 Years to < 5 Years          0
                                                               30 to < 90 Days               0
                                                               5 or More Years               0
...                                                                                        ...
WVWU-TX1 West Virginia University Hospitals Inc. West Virginia 30 to < 90 Days               0
                                                               6 Months to < 1 Year          0
                                                               90 Days to < 6 Months         0
                                                               < 30 Days                     0
                                                               All Time                      0

                                                                                      Heart
Center Name                                      Center States Wait Time
ALCH-TX1 Children's of Alabama                   Alabama       1 Year to < 2 Years        2
                                                               2 Years to < 3 Years       1
                                                               3 Years to < 5 Years       0
                                                               30 to < 90 Days            0
                                                               5 or More Years            0
...                                                                                     ...
WVWU-TX1 West Virginia University Hospitals Inc. West Virginia 30 to < 90 Days            0
                                                               6 Months to < 1 Year       0
                                                               90 Days to < 6 Months      1
                                                               < 30 Days                  0
                                                               All Time                   1

[4768 rows x 4 columns]