In [30]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import make_classification

In [31]:
import pandas as pd 
import numpy as np
# import datetime as dt
import matplotlib.pyplot as plt
from sklearn import utils

In [32]:
survival_by_type= pd.read_csv('Resources/survival_donor_type_df.csv')
survival_by_type

,_id,Region,Organ,Donor_Type,Years_Post_Transplant,Number_Functioning_or_Alive,Survival_Rate
0,6032c5d337ca244bc48d66db,U.S.,Kidney,Cadaveric,1 Year,42355,93.2
1,6032c5d337ca244bc48d66dc,U.S.,Kidney,Living,1 Year,21709,97.5
2,6032c5d337ca244bc48d66dd,U.S.,Kidney,Cadaveric,3 Year,35404,85.1
3,6032c5d337ca244bc48d66de,U.S.,Kidney,Living,3 Year,20611,92.5
4,6032c5d337ca244bc48d66df,U.S.,Kidney,Cadaveric,5 Year,28612,74.4
5,6032c5d337ca244bc48d66e0,U.S.,Kidney,Living,5 Year,18723,85.6
6,6032c5d337ca244bc48d66e1,U.S.,Liver,Cadaveric,1 Year,22397,89.1
7,6032c5d337ca244bc48d66e2,U.S.,Liver,Living,1 Year,992,88.0
8,6032c5d337ca244bc48d66e3,U.S.,Liver,Cadaveric,3 Year,18876,80.0
9,6032c5d337ca244bc48d66e4,U.S.,Liver,Living,3 Year,818,82.0
10,6032c5d337ca244bc48d66e5,U.S.,Liver,Cadaveric,5 Year,16520,71.9
11,6032c5d337ca244bc48d66e6,U.S.,Liver,Living,5 Year,741,77.3

In [33]:
X= survival_by_type.drop(columns=['_id', 'Region', 'Survival_Rate', 'Number_Functioning_or_Alive'])
y= survival_by_type[['Survival_Rate']]
# y
X.head()

    Organ Donor_Type Years_Post_Transplant
0  Kidney  Cadaveric                1 Year
1  Kidney     Living                1 Year
2  Kidney  Cadaveric                3 Year
3  Kidney     Living                3 Year
4  Kidney  Cadaveric                5 Year

In [38]:
# from sklearn.preprocessing import LabelEncoder

# label_encoder = LabelEncoder()
# # # Encode labels in columns
# X_encoded= X_train.apply(LabelEncoder().fit_transform)
# X_encoded
# X_encoded_array= np.array(X_encoded)
# X_encoded_array
#

In [39]:
 # Use train_test_split to create training and testing data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [41]:
from tensorflow.keras.utils import to_categorical

X_train_categorical = to_categorical(X_train)
X_test_categorical = to_categorical(X_test)

ValueError: invalid literal for int() with base 10: 'Liver'

In [42]:
from sklearn.ensemble import RandomForestRegressor

model_1 = RandomForestRegressor(n_estimators=200)
model_1.fit(X_train_scaled, y_train_scaled)

model_1_training_score = round(model_1.score(X_train_scaled, y_train)*100,3)

base_accuracy = round(model_1.score(X_test_scaled, y_test)*100,3)

print(f"Training Data Score: {model_1_training_score} %")
print(f"Testing Data Score: {base_accuracy} %")

In [35]:

model_1 = RandomForestClassifier(n_estimators=200)
model_1.fit(X_train_scaled, y_train)

# model_1_training_score = round(model_1.score(X_train_scaled, y_train)*100,3)
# base_accuracy = round(model_1.score(X_test_scaled, y_test)*100,3)

# print(f"Training Data Score: {model_1_training_score} %")
# print(f"Testing Data Score: {base_accuracy} %")

In [32]:
# #Import scikit-learn metrics module for accuracy calculation
# from sklearn import metrics
# # Model Accuracy, how often is the classifier correct?
# print("Accuracy:",metrics.accuracy_score(y_test, y_pred))